"use client"
import localFont from "next/font/local";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import { AuthProvider } from "@/components/AuthContext";
import { usePathname } from 'next/navigation';

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});


export default function RootLayout({ children }) {
  const pathname = usePathname();
  const isAuthPage = pathname.startsWith('/auth');

  return (
    <html lang="en">
      <>
        <title>Red Product</title>
        <meta name="description" content="Generated by create next app" />
      </>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Toaster position="top-right" reverseOrder={true} toastOptions={{ duration: 5000, }} />
        {isAuthPage ? (
          children
        ) : (
          <AuthProvider>{children}</AuthProvider>
        )}
      </body>
    </html>
  );
}
